@HostAddress = https://localhost:7165

GET {{HostAddress}}/api/countries
Accept: application/json
###

GET {{HostAddress}}/api/countries?page=2&pageSize=5
Accept: application/json
###

GET {{HostAddress}}/api/countries/usa
Accept: application/json
###

GET {{HostAddress}}/api/countries/bol
Accept: application/json
###

GET {{HostAddress}}/api/countries/s
Accept: application/json
###

GET {{HostAddress}}/api/regions
Accept: application/json
###

GET {{HostAddress}}/api/languages
Accept: application/json
###

