@HostAddress = https://localhost:7165

GET {{HostAddress}}/api/countries
Accept: application/json
###

GET {{HostAddress}}/api/countries?page=2&pageSize=5
Accept: application/json
###

GET {{HostAddress}}/api/countries?searchTerm=me&sortDesc=true
Accept: application/json
###

GET {{HostAddress}}/api/countries/usa
Accept: application/json
###

GET {{HostAddress}}/api/countries/bol
Accept: application/json
###

GET {{HostAddress}}/api/countries/x
Accept: application/json
###

GET {{HostAddress}}/api/regions
Accept: application/json
###

GET {{HostAddress}}/api/regions?searchTerm=c&sortDesc=true
Accept: application/json
###

GET {{HostAddress}}/api/languages
Accept: application/json
###

GET {{HostAddress}}/api/languages?searchTerm=x&sortDesc=true
Accept: application/json
###

